feat: add redux
batyril/2024-2-VK-EDU-Frontend-I-Nazyrov pull request #10
Opened 2024-11-30 20:00 UTC by batyril

для тестового стенда

2024-12-01 19:56 UTC, sh4rkizz requested changes
Очень круто получается, ты молодец
Давай в рамках этой дз проработаем подгрузку данных и страницу профиля

И может немного стилестически подкорректируем вложения

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Предлагаю попробовать уместить в один экран страницу профиля, чтобы не приходилось скроллить

Из доработок, предлагаю поле "загрузите аватарку" сделать hidden input [скрыть его и активировать загрузку по клику на кружочек с аватаркой]

Докинуть соответственно ховер на этот кружок, а также немного уменьшить его

<img width="512" alt="изображение" src="https://github.com/user-attachments/assets/b38136f3-bab1-478f-a63a-643440bab25b">


Было бы круто увидеть что-то похожее

<img width="244" alt="изображение" src="https://github.com/user-attachments/assets/9ad2c28c-8faa-4e28-9606-2163669ca32e">

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Я бы реогранизовал так же порядок элементов [но это личные пожелания]
Предлагаю такой порядок

<img width="357" alt="изображение" src="https://github.com/user-attachments/assets/1403b1ec-aa09-400f-b24a-1a22386e5c72">

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Шапка профиля как-то выбивается из общей стилизации страниц
Кнопки везде по краям, title - по центру

В профиле же почему-то слиплось в центре

<img width="795" alt="изображение" src="https://github.com/user-attachments/assets/61a48de2-f448-431e-80e3-e681cca084cc">

<img width="794" alt="изображение" src="https://github.com/user-attachments/assets/b9aff2db-c357-4275-bff6-0050fc0ee551">

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Предлагаю между картинкой и текстом добавить отступ, чтобы не выглядело прилипшим

<img width="742" alt="изображение" src="https://github.com/user-attachments/assets/bdcc9610-1dfd-4221-91f3-0117a44c4760">

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Как улучшение системы лоадеров, когда бесконечный скролл используешь, лучше лоадер стаить там, где подгружаешь

Сейчас ситуация в чате следующая:
\- Я вижу 20 сообщений, хочу увидеть еще 20 старых
\- Прокручиваю страницу
\- Лоадер перекрывает мне уже загруженные 20 до тех пор, пока новые 20 не будут получены с бекенда

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Можно UX-но сделать краше, скруглив края картинок и аудиозаписей

<img width="442" alt="изображение" src="https://github.com/user-attachments/assets/ff265409-d93b-4877-9db5-efbbf7e7af3b">


После скругления примерно так получится
Здесь не очень подобрано скругление с учетом паддинга и скругления внешнего блока
Но идея надеюсь понятна)

Вообще советую всегда использовать четные значения пикселей для скруглений, паддингов, марджинов


<img width="357" alt="изображение" src="https://github.com/user-attachments/assets/0d29efdf-466c-492f-9b66-4ae0c2bd556d">

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Если хочешь еще сильнее улучшить UX - позволь пользователям приближать / отдалять картинки
Есть прикольная либа для таких штук - `viewerjs`, конкретно класс `Viewer`

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Каждый запрос при скролле на странице https://batyril.github.io/2024-2-VK-EDU-Frontend-I-Nazyrov/#/contacts стучится сначала в `status: 301`

`GET 301 https://vkedu-fullstack-div2.ru/api/users?page=8&page_size=10&search=`
`GET 200 https://vkedu-fullstack-div2.ru/api/users/?page=8&page_size=10&search=`

Происходит это, потому что основная часть URL должна всегда завершаться `/` 
[по крайней мере для django приложений]

<img width="668" alt="изображение" src="https://github.com/user-attachments/assets/b4df048b-4d4c-44fb-9f43-5e4c4179fa0c">

2024-12-01 19:56 UTC, sh4rkizz commented on react-chat/src/api/messages/index.js
> +      headers: getHeaders('application/json', accessToken),
Давай сунем `toastify` в каждый `catch` блок, когда ошибка явно не обработана сервером

Клиент без интернета - как явный кейс
[можно в целом и явно на [navigator.onLine](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/onLine) проверять, но разве ж это круто]
Да и 502ые например стоит обработать 


<img width="1257" alt="изображение" src="https://github.com/user-attachments/assets/ec97ec65-53db-47df-8426-68a054bf4dd9">

2024-12-03 22:24 UTC, sh4rkizz approved these changes
lgtm!

2024-12-06 22:11 UTC, HaseProgram commented
Зачтено, 7!

2024-12-06 22:11 UTC, merged