Dz#2
batyril/2024-2-VK-EDU-Frontend-I-Nazyrov pull request #2
Opened 2024-09-25 19:29 UTC by batyril

# Домашнее задание №

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1MarBur1 проверить его.

Что было сделано:
* Стилизовал страницу отправки сообщений
* Реализовал сохранение и загрузку сообщений с localStorage
* Реализовал очищение поля после отправки сообщения 
* Переделал базовый шаблон под Vite и залил на Github Pages 
* Для оптимизации создания новых сообщений использовал HTML-тег <template>

2024-09-29 19:50 UTC, 1MarBur1 requested changes

2024-09-29 19:50 UTC, 1MarBur1 commented on simple-chat/src/js/handlers.js
> +  if (text.length <= 1) {
Почему не могу отправить сообщение длиной 1?

Давай заменим на !text.length

2024-09-29 19:50 UTC, 1MarBur1 commented on simple-chat/src/js/localStorage.js
> +    });
Для чего нам db.js? разве мы не можем доставать storedMessages прямиком из localStorage? Сейчас получается мы храним одни и те же данные в 2х разных местах, для чего?

2024-09-29 19:50 UTC, 1MarBur1 commented on simple-chat/src/js/render.js
Сейчас на каждое новое сообщение мы ререндерим весь список, представим что сообщений бесконечно много, кажется у всех наших юзеров взорвутся устройства. Можем ли мы как-то решить эту проблему? Рендерить только новое сообщение?

2024-09-30 19:58 UTC, batyril commented on simple-chat/src/js/localStorage.js
> +    });
Ну да, он по сути не нужен, дублирование данных, оставил только один источник истины

2024-09-30 19:59 UTC, batyril commented on simple-chat/src/js/render.js
Да, можно оптимизировать рендеринг, чтобы не рендерить весь список сообщений заново при добавлении нового сообщения.
- При первой загрузке страницы рендерим все сообщения, загруженные из localStorage.
- Для добавления новых сообщений рендерим только одно сообщение, непосредственно добавляя его в DOM.

2024-10-02 10:55 UTC, 1MarBur1 submitted a review, later dismissed
@HaseProgram @martinkomitsky @kgrechin approved

2024-10-02 20:47 UTC, HaseProgram submitted a review, later dismissed
Отлично! 12!

2024-10-02 20:49 UTC, HaseProgram approved these changes

2024-10-02 20:57 UTC, HaseProgram commented
Не могу смержить. Какие-то протекшн права для ветки? В любом случае аппрув на мерж даю.

2024-10-02 22:35 UTC, merged