Dz#6
batyril/2024-2-VK-EDU-Frontend-I-Nazyrov pull request #6
Opened 2024-10-30 22:17 UTC by batyril

# Домашнее задание № 6

Прошу @martinkomitsky, @haseprogram, @kgrechin или @1MarBur1 проверить его.

Что было сделано:
* добавил react-router с HashRouter
* добавил страницу профиля

2024-11-05 11:55 UTC, sh4rkizz requested changes

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/Header/Header.module.scss
> +.header {
Касаемо стилей хедера

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/Header/Header.module.scss
> +.header {
Давай поправим выравнивание

<img width="106" alt="изображение" src="https://github.com/user-attachments/assets/358fa729-e0ae-40f3-9348-d8075ef56b7a">
<img width="188" alt="изображение" src="https://github.com/user-attachments/assets/eae9a004-35ff-4168-bfed-df83abf438fd">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/SendMessageForm/SendMessagesForm.jsx
> +function SendMessagesForm({ userId }) {
Предлагаю убрать автокомплит поля ввода, а также повесить на форму novalidate и просто не отправлять сообщения, если `!message.trim()`

не хватает trim() на всех полях ввода

<img width="923" alt="изображение" src="https://github.com/user-attachments/assets/2fbc1483-1e65-4e5a-a508-8f4b01c93508">

<img width="170" alt="изображение" src="https://github.com/user-attachments/assets/6d551a2f-c2ef-4611-8b4f-8636661e0176">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/SendMessageForm/SendMessagesForm.jsx
> +function SendMessagesForm({ userId }) {
При отправке длинного сообщения на странице списка чатов появляется скролл, давай обрезать)

<img width="922" alt="изображение" src="https://github.com/user-attachments/assets/9716b1d0-2eec-4927-b9f7-44af4211c7f0">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/SendMessageForm/SendMessagesForm.jsx
> +function SendMessagesForm({ userId }) {
Аналогично следует уменьшить количество строк, если сообщение длинное - предлагаю 1-2

[`-webkit-clamp`](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) в помощь

<img width="926" alt="изображение" src="https://github.com/user-attachments/assets/14cda82e-8aec-4e87-b119-d9b813a06c09">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/ChatModal/ChatModal.jsx
> +        <h2>Создать новый чат</h2>
Предлагаю доработать модалку
<img width="352" alt="изображение" src="https://github.com/user-attachments/assets/b440550d-7522-41c2-a0a9-c97ed28c31d3">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/ChatModal/ChatModal.jsx
> +        <h2>Создать новый чат</h2>
- убрать автокомплит
- повесить автофокус на поле ввода, чтобы при открытии сразу можно было вписывать текст
- добавить обработку нажатия вне модалки и клавиши Escape [+ event.preventDefault()]

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/ChatModal/ChatModal.jsx
> +        <h2>Создать новый чат</h2>
вот эти кнопки предлагаю растянуть по ширине, чтобы не было пустого пространства посередине

<img width="278" alt="изображение" src="https://github.com/user-attachments/assets/8d5e8ef3-2de8-48e3-8ba5-db91a15e3260">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/pages/pageProfile/PageProfile.jsx
> +  );
По странице профиля предлагаю для формы novalidate, и написать кастомную валидацию
\+ ошибки под полями [сбрасываются в когда в поле начинаешь что-то вводить [но только под тем полем куда вводишь]]

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/pages/pageProfile/PageProfile.jsx
> +  );
Было бы хорошо не разрешать пользователю расширять bio за границы экрана

<img width="793" alt="изображение" src="https://github.com/user-attachments/assets/c75031b2-851b-43ae-83b7-c652ca4ff02f">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/pages/pageProfile/PageProfile.jsx
> +  );
Нужно какую-то индикацию того, что сохранилось успешно
модалка/алерт/текст на странице на несколько секунд

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/pages/pageProfile/PageProfile.jsx
> +  );
предлагаю, чтобы кнопка "Сохранить" была по умолчанию в состоянии `disabled`, и разблокировалась только после того, как изменено какое-то из полей или ткнули кнопку "очистить"

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/SendMessageForm/SendMessagesForm.jsx
> +function SendMessagesForm({ userId }) {
касается так же имени собеседника

<img width="966" alt="изображение" src="https://github.com/user-attachments/assets/3d40d714-d7b7-47a9-b20c-0d705dd116da">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/SendMessageForm/SendMessagesForm.jsx
> +function SendMessagesForm({ userId }) {
Аналогично в шапке 

<img width="925" alt="изображение" src="https://github.com/user-attachments/assets/dff9c728-2839-488a-9b4c-8af8a8cb3c3a">

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/components/App/App.jsx
> +    </ChatContext.Provider>
Касаемо роутинга - выглядит хорошо
Было бы классно иметь 404 страницу, на которой есть кнопка для возвращения на главную

2024-11-05 11:55 UTC, sh4rkizz commented on react-chat/src/pages/PageChat/PageChat.jsx
> +function PageChat({ chats }) {
странно, но не работает скролл на странице чата

<img width="925" alt="изображение" src="https://github.com/user-attachments/assets/a3522a9a-e595-46df-8a2f-39c40e382e26">

2024-11-05 11:56 UTC, sh4rkizz commented on react-chat/src/pages/pageProfile/PageProfile.jsx
> +      <Header name={'Профиль'} img={details.img} />
Кажется странным использование компонента header, который предназначен для Chat
Стоит завести отдельно для Profile

<img width="563" alt="изображение" src="https://github.com/user-attachments/assets/ad3f907f-71db-485a-8cd3-465f2e28412a">

2024-11-06 15:05 UTC, sh4rkizz submitted a review, later dismissed
lgtm

2024-11-06 15:06 UTC, sh4rkizz approved these changes
lgtm v2

2024-11-07 18:23 UTC, merged

2024-11-07 18:23 UTC, martinkomitsky commented
12!