ДЗ 7
batyril/2024-2-VK-EDU-Frontend-I-Nazyrov pull request #8
Opened 2024-11-12 14:27 UTC by batyril

# Домашнее задание №7

Прошу @martinkomitsky, @haseprogram, @kgrechin или @sh4rkizz проверить его.

Что было сделано:

- Интеграция API для работы с чатом: Были интегрированы API для отправки и получения сообщений, а также для управления чатами.

- Регистрация: Реализована страница регистрации пользователей с использованием соответствующего API.

- Страница логина: Создана страница для входа пользователей с использованием API аутентификации.

- Отправка сообщений: Реализована возможность отправки сообщений через API.

- Получение сообщений через WebSockets: Интегрированы WebSockets для получения сообщений в реальном времени.

https://batyril.github.io/2024-2-VK-EDU-Frontend-I-Nazyrov/

2024-11-13 09:07 UTC, sh4rkizz requested changes

2024-11-13 09:07 UTC, sh4rkizz commented on react-chat/src/components/Forms/ProfileForm.jsx
> +        label='bio*'
Довольно большое пространство появляется между сообщением и датой
Если хочешь сделать по-хитрому, посмотри в веб-версии ТГ как можно сделать

<img width="772" alt="изображение" src="https://github.com/user-attachments/assets/988bdf1c-6c68-4068-ba68-a82bc6df20b1">

2024-11-13 09:07 UTC, sh4rkizz commented on react-chat/src/components/Forms/ProfileForm.jsx
> +        label='bio*'
Немного пустовато выглядит шапка страницы создания чата
<img width="461" alt="изображение" src="https://github.com/user-attachments/assets/7c804a8f-b100-44c4-b8c5-5f0c8f923cda">

2024-11-13 09:07 UTC, sh4rkizz commented on react-chat/src/components/Forms/ProfileForm.jsx
> +        label='bio*'
Предлагаю убрать margin с хедера, нарушает визуальное выравнивание

<img width="417" alt="изображение" src="https://github.com/user-attachments/assets/02602110-4f78-4126-a1d0-d6875b5ccd03">

2024-11-13 09:07 UTC, sh4rkizz commented on react-chat/src/components/Forms/ProfileForm.jsx
> +        label='bio*'
Пагинация для списка чатов выглядит странно, здесь корректнее сделать бесконечную прогрузку

<img width="539" alt="изображение" src="https://github.com/user-attachments/assets/04ed4361-498d-4ca8-9571-144fb8cc1061">

2024-11-13 09:07 UTC, sh4rkizz commented on react-chat/src/components/Forms/ProfileForm.jsx
> +        label='bio*'
Кажется потеряно/забыто отображение прочитанности 
[пока это хардкод галка, но стоит добавить, чтобы стили соответствовали финальному результату]
<img width="361" alt="изображение" src="https://github.com/user-attachments/assets/fffe21df-a4f6-423c-9cba-3c4120748b43">

2024-11-13 09:08 UTC, sh4rkizz commented on react-chat/src/components/Forms/ProfileForm.jsx
> +        label='bio*'
Странновато выглядят директории, названные капсом, это воркфлоу где-то?
<img width="324" alt="изображение" src="https://github.com/user-attachments/assets/4b5b9b21-5db8-4632-a8a2-1e27ffab3341">

2024-11-14 20:54 UTC, sh4rkizz approved these changes
lgtm!

2024-11-15 09:57 UTC, martinkomitsky commented
10

2024-11-15 09:57 UTC, merged